name: Qlok
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcbbcb'
    - '#171017'
    - '#fcecdf'
    - '#6c6165'
    - '#473c3a'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
